name = "lapce-php"
version = "0.1.0"
author = "Hugo Nicolas <hugo.nicolas.hn@gmail.com>"
display-name = "PHP"
description = "Lapce LSP plugin for PHP, powered by Phan"
wasm = "bin/lapce-php.wasm"

[activation]
language = ["php"]
workspace-contains = ["*/*.php"]
